name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Execute Remote Deployment
    runs-on: ubuntu-24.04
    environment:
      name: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH to management server and Deploy
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/management_key
          chmod 600 ~/.ssh/management_key

          ssh -i ~/.ssh/management_key \
            -p ${{ secrets.SSH_PORT }} \
            -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_PUBLISHER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e

          cd /home/${{ secrets.SSH_PUBLISHER }}/WK_test_infra/ansible

          ansible-playbook -i hosts.ini service_deployment.yml

          EOF